select * from customer_behavior.customer limit 10;

SHOW TABLES;
use customer_behavior;
show tables;


-- Q1. What is the total revenue generated by male vs. female customers?
SELECT
	gender,
    SUM(purchase_amount) as revenue
    from customer
    group by gender;
    
-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'yes' and purchase_amount >= (select AVG(purchase_amount)from customer);


-- Q3. Which are the top 5 products with the highest average review rating?
use customer_behavior;
select item_purchased, ROUND(AVG(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average purchase amounts between Standard and Express Shipping.
select shipping_type,
	ROUND(AVG(purchase_amount),2)
	from customer
	where shipping_type in ('standard','express') 
	group by shipping_type ;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 
	ROUND(SUM(CASE when discount_applied = 'yes' THEN 1 ELSE 0 END) * 100/COUNT(*),2) as discount_percentage
    from customer
    group by item_purchased
    order by discount_percentage desc
    limit 5;
    


-- Q7. Segment customers into New, Returning, and Loyal based on their 
-- total number of previous purchases, and show the count of each segment.
SELECT 
    CASE
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    
    COUNT(*) AS customer_count

FROM customer

GROUP BY customer_segment;
    
        
-- Q8. What are the top 3 most purchased products within each category?
SELECT *
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,

        RANK() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS ranking

    FROM customer
    GROUP BY category, item_purchased
) ranked_products

WHERE ranking <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status,
    COUNT(*) AS customer_count,
    
    ROUND(AVG(previous_purchases), 2) AS avg_previous_purchases

FROM customer

WHERE previous_purchases > 5

GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT 
    CASE
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 45 THEN '36-45'
        ELSE '46+'
    END AS age_group,

    SUM(purchase_amount) AS total_revenue,

    ROUND(
        (SUM(purchase_amount) * 100.0) / 
        (SELECT SUM(purchase_amount) FROM customer),
        2
    ) AS revenue_percentage

FROM customer

GROUP BY age_group

ORDER BY total_revenue DESC;